### PR TITLE
Add code block background color change while running

### PR DESCRIPTION
**Pull request by lukejahnke**
I have started using this plugin with some code blocks that are long running, perhaps not the best idea but it seems to work okay so far. Because of this, it would be nice to have some indication of which code blocks are currently running as well as when they have stopped.

This PR is a quick implementation using the "sign" feature in vim to change styling while the code is executing.

### CODE REVIEW

**Comment by lukejahnke** [comment]
I'm new to vimscript so there are quite a few things I wasn't sure of when creating this PR.

1) Whether there is a better place within the file for the `highlight` and `sign define` lines to be placed (i.e within `medieval#eval`). Or even if it would be a better practice to create a syntax directory/file.

2) The `setlocal signcolumn=no` line looks like it could annoy users who use other plugins/configurations that make use of the signcolumn. I'm not sure how common that is though, as the line number column is separate to this. I considered only setting to no when `sign list`/`sign_getdefined` is empty or the value was the default value of "auto".

3) I wasn't sure the most appropriate style to use and landed on "Underlined" just because it looked fine for my default vim setup.

4) Perhaps I should be checking `has("signs")`?

**Comment by gpanders** [comment]
I think it would be better to simply provide a hook for when execution finishes, which would allow users to do any kind of customization they like (including what you've proposed here).

I just pushed a change to the `callback` branch that enables this. You can call `medieval#eval('', {'callback': function('SomeFunction')})`, where `SomeFunction` is called when evaluation completes.

So to implement the background color change, you can:

1. Modify the background color and set signs or whatever
2. Call `medieval#eval` as above
3. In the callback function, reset the background color and clear the signs.

I didn't push this to master yet. Would you mind checking out the `callback` branch and let me know if it allows you to do what you want to do?

**Comment by lukejahnke** [comment]
The `callback` approach looks good but in the current state does not allow me to do what I wanted.

To set the signs on just the lines for a running code block I would need access to the line numbers for start and end. In the current state, I think the only way to get these would be to recalculate them by re-implementing the `startpat` regex and related code.

Perhaps a hook called prior to execution beginning could also be supported that will be called prior to `s:jobstart` and passed `context`?

**Comment by gpanders** [comment]
The start and end line numbers are included in the context (the first argument passed to the callback).

**Comment by lukejahnke** [comment]
But that is for the the current callback which is only used to "reset the background color and clear the signs" (step 3) and is called when the code block has finished executing.

I need to be able to apply the signs to the appropriate line numbers (step 1) prior to the code block executing.

**Comment by gpanders** [comment]
Ah right. I can expose another callback that is fired right before execution begins that also has access to the context.

**Comment by gpanders** [comment]
7c27fe6e10263622b1cd47c776c1a88fe4c9485a adds a `'setup'` key to the options dict that accepts a function that is called just before the block is evaluated. I also renamed `'callback'` to `'complete'`.

The `'setup'` function accepts the block context as well as the source of the block as a list of lines, so you can make modifications based on the content of the block (or modify the block contents).

**Comment by lukejahnke** [comment]
Thank you, this works perfectly for what I need.

One small suggested improvement for the documentation `doc/medieval.txt`:
- Instead of `let s:start = reltime()` it now makes sense to store the value within the context (making sure not to clobber the already existing `ctx['start']`), so `let a:ctx['start_time'] = reltime()`. This will work correctly when multiple code blocks are simultaneously executing, where as the current example would break.

Thanks again!

**Comment by gpanders** [comment]
Thanks for the suggestion, I'll update the example in the docs.

**Comment by gpanders** [comment]
Ok I just merged the `callback` branch. If you have any follow up bugs/questions/suggestions, feel free to make another issue or PR. Thanks for your help testing!

**Pull request closed without merging**
